version: '3.7'

# Default image name will be CustomerAPI
# build 'docker-compose' build from this directory
# run 'docker-compose up --build' 
services: 
    app: 
        build: 
            # path to dockerfile
            context: .
        ports: 
            # map port 8000 in host machine to 8000 in container
            - "8000:8000"
        volumes: 
            #synchronize app directory
            - ./CustomerAPI:/app
        # run server listening on all ip address on docker and map it to port 8000,
        # which is inturn forwarded to port 8000 on host machine
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1